name: Shortcuts
author: narrowtux
version: 0.2.1
main: com.narrowtux.shortcuts.ShortcutsMain
commands:
    shortcut:
        usage: /sh [add|remove|list]
        aliases: [sh]
        permission: shortcuts.use
depends: [NarrowtuxLib]
permissions: 
    shortcuts.*:
        description: Gives you access to all features of Shortcuts
        children:
            shortcuts.use: true
    shortcuts.use:
        description: Gives you access to the main features of the plugin (add, update, remove, list)
        default: true