name: Shortcuts
author: narrowtux
version: 0.1
main: com.narrowtux.shortcuts.ShortcutsMain
commands:
    shortcut:
        usage: /sh [add|remove|list]
        aliases: [sh]
        
depends: [NarrowtuxLib]